ktor {
    deployment {
        host = "0.0.0.0"
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.tuempresa.osornomarket.backend.ApplicationKt.module ]
    }
}

storage {
    driverClassName = "org.postgresql.Driver"
    jdbcURL = "jdbc:postgresql://ep-noisy-base-aij83iv3.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require"
    user = "neondb_owner"
    password = "npg_p9gX8SLkmsKn"
}

jwt {
    secret = "mi_secreto_super_seguro_123"
    issuer = "http://0.0.0.0:8080"
    audience = "http://0.0.0.0:8080"
    realm = "OsoMarket Backend"
}
